apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}  
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
      - name: {{ .Values.pvcname1 }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvcname1 }}
#        name: nginx
        #hostPath:
         # path: /root/nginx.conf
      - name: {{ .Values.pvccode }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvccode }}
      - name: {{ .Values.pvcname2 }}
        configMap:
          name: nginx-config   
      containers:
      - name: {{ .Release.Name }}
        image: nginx:latest 
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
 #       command: ["/bin/bash"]
#        args: ["-c", "apt update -y && apt install nodejs npm -y"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/code/"
         # mountPath: "/etc/nginx/conf.d/"
          name: {{ .Values.pvccode }}
        - mountPath: /etc/nginx/conf.d/
          name: {{ .Values.pvcname2 }}
        - mountPath:  /etc/nginx/ 
          name: {{ .Values.pvcname1 }}
        - mountPath:  /var/log/nginx/
          name: {{ .Values.pvcname1 }}
