
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-code-volume
  namespace: lhc
  labels:
    name: {{ .Release.Name }}-code-volume
spec:
  storageClassName: lhc-nfs-csi
  capacity:
    storage: {{ .Values.capacity_code }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/code/"
    server: "172.31.38.220"

