
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-code-volume
  namespace: lhc
  labels:
    name: {{ .Release.Name }}-code-volume
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-code-volume
  storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
