apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-volume
  namespace: lhc
  labels:
    name: {{ .Release.Name }}-db-volume
spec:
  #storageClassName: lhc-nfs-csi
  capacity:
    storage: {{ .Values.capacity_db }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/database/"
    server: "172.31.38.220"
---
