
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-volume
  namespace: lhc
  labels:
    name: {{ .Release.Name }}-db-volume
spec:
  selector:
    matchLabels: 
      name: {{ .Release.Name }}-db-volume
  #storageClassName: lhc-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
