

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  namespace: lhc
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: {{ .Release.Name }}-db
        image: mariadb:latest
        env:
          - name: {{ .Values.dbenv }}
            valueFrom:
              secretKeyRef:
                name:  {{ .Values.secretname }}
                key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name:  {{ .Values.pvcdatabase }}
          mountPath:  /var/lib/mysql
      volumes:
      - name: {{ .Values.pvcdatabase }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvcdatabase }}  
