apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cobrowser
  namespace: lhc
spec:
  selector:
    app: {{ .Release.Name }}-cobrowser
  ports:
  - port: {{ .Values.svcport_cobrowser }}
    targetPort: {{ .Values.tgport_cobrowser }}
---
