apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-resque
  namespace: lhc
spec:
  selector:
    app: {{ .Release.Name }}-php-resque
  ports:
  - port: {{ .Values.svcport_phpresque }}
    targetPort: {{ .Values.tgport_phpresque }}
---