apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejshelper
  namespace: lhc
spec:
  selector:
    app: {{ .Release.Name }}-nodejshelper
  ports:
  - port: {{ .Values.svcport_nodejshp }}
    targetPort: {{ .Values.tgport_nodejshp }}
---