apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: lhc
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
  - port: {{ .Values.svcport_redis }}
    targetPort: {{ .Values.tgport_redis }}
