# For service lhc-app
svcport_lhc_app: 8080
tgport_lhc_app: 80

# For service php
svcport_php: 9000
tgport_php: 9000

# For service nodejs helper
svcport_nodejshp: 8000
tgport_nodejshp: 3000

# For service cobrowser
svcport_cobrowser: 31130
tgport_cobrowser: 31130

# For service mysql
svcport_db: 3306
tgport_db: 3306

# For service PHP resque
svcport_phpresque: 31082
tgport_phpresque: 9000

# For service redis
svcport_redis: 30379
tgport_redis: 6379

# For volume
pvclhcvolume: lhc-volume
pvcnginxconfig: lhc-nginx-config
pvccode: lhc-code-volume 
pvcdatabase: lhc-db-volume
pvcphp: lhc-php-volume
pvcnginx: lhc-nginx-volume

capacitylhc: 600Mi
capacity_db: 1Gi
capacity_code: 1Gi
capacity_nginx: 300Mi

# For database
dbenv: MYSQL_ROOT_PASSWORD
secretname: lhc-secret-db