kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
  - name: matomo-port
    port:  {{ .Values.svcport }}
    targetPort:  {{ .Values.ports }}
    nodePort: {{ .Values.nodeport }}
---
