apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/nginx/"
    server: "172.31.28.220"
