apiVersion: v1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }} 
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
