kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
  - name: mysql-port
    port:  {{ .Values.svcport }}
    targetPort: {{ .Values.mysqlport }}
    nodePort: 31081
