apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  labels:
    name: {{ .Release.Name }}
spec:
  #storageClassName: mystorageclass
  capacity:
    storage: {{ .Values.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/database/"
    server: "172.31.38.220"
